### ISSUE TITLE
get JsonArray from claims 

### ISSUE THREAD

**Issue by TobiasReich** [nefilim/kjwt#13]
I have a claimSet in the JWT that is seen as a `JsonArray` (even though in the end its just a list of Strings).

However, there is no claimValue function for that since they all check for `jsonPrimitive?`

This leads to the exception:

`java.lang.IllegalArgumentException: Element class kotlinx.serialization.json.JsonArray is not a JsonPrimitive`

Is there any way to get that? In the end it is just a StringList but even `claimValueAsList` throws that Exception.

**Comment by peterfigure** [comment]
could you give me a concrete example please?

**Comment by TobiasReich** [comment]
Basically the simplified payload looks like that:
 
```
{
  "uId": 2905,
  "productTags": [
    "abcd"
  ],
  "iat": 1635698037,
  "nbf": 1629967409,
  "exp": 1637743409
}
```
and I need to get the productTags out.

**Comment by nefilim** [comment]
thank you for the bug report, please try v0.4.9 or later and let me know if that solves your problem?

**Comment by TobiasReich** [comment]
Looks nice, thanks.

Just a few thoughts:

1. These lists are set to Strings. I could imagine others having other data types. But for my use case this is perfect. So no need for generic types etc.
2. All the other claim methods return an Option<> whereas this one directly returns a List. That is great for my use case but I'm not sure if others prefer the Option<T> return value since this returns an empty list instead of Option.None. To me that sounds fine since in case that becomes just an empty list. Just not consistent with the other calls.

So thanks a lot. I like it. Its a simple, compact library. Just what I needed.

**Comment by nefilim** [comment]
Good comments thank you - I'll think about a more consistent interface, there might be value (no pun intended) in denoting the absence of the array claim.
