### ISSUE TITLE
Android support only API 26+

### ISSUE THREAD

**Issue by TobiasReich** [nefilim/kjwt#18]
And maybe a heads up for everyone who wants to use this for an Android Project.

Since the Base64 class is used, it allows the usage of this library only from Android API 26+.

https://developer.android.com/reference/java/util/Base64

Versions below will get trouble with the call
`fun jwtDecodeString(data: String): String = String(Base64.getUrlDecoder().decode(data))`
stating a `NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;`

Maybe it would be good to mention this in case someone is interested in this.

**Comment by nefilim** [comment]
Thanks, good to know, I don't know anything about Android :) Will add to the README
