### ISSUE TITLE
JWT.decode returning AlgorithmMismatch in 0.6.0

### ISSUE THREAD

**Issue by sproctor** [nefilim/kjwt#26]
I'm trying to decode a JWT from Auth0 with alg "RS256". Works fine with 0.5.3, but is broken in 0.6.0 and gives that result.

**Comment by sproctor** [comment]
Sorry, this is my fault. Something changed between the two versions that caused proguard to break things. I don't know if there's anything to be done on the library side. I just added a keep rule for everything in the package and it resolved the issue. Maybe a proguard file would be nice.

**Comment by sproctor** [comment]
After a tiny bit of research, I see the change that caused the breakage for me: 580ae029de5c1b56bef852a9379f4788b8d04028

I have rules to keep classes marked with `@Serializable`, but not classes who only have members with that annotation.

**Comment by nefilim** [comment]
oh interesting, I'm sorry @sproctor, I don't know anything about Android development or Proguard but open to suggestions!
