### ISSUE TITLE
Expiration validation failure due to TimeZone differences

### ISSUE THREAD

**Issue by ziek-za** [nefilim/kjwt#30]
Hello

I am receiving TokenExpired failures as the claim validation (see snippet below) doesn't consider the timezone in the comparison.

```
val expired: ClaimsValidator = requiredOptionClaim("expired", { expiresAt() }, { it.isAfter(LocalDateTime.now()) }, KJWTValidationError.TokenExpired)
```

From the extension function which is used to deserialize the expiration field (`"exp"`) I can see it uses UTC timezone (see snippet below)

```
internal fun Long.fromJWTNumericDate(): LocalDateTime = LocalDateTime.ofEpochSecond(this, 0, ZoneOffset.UTC)
```

The difference in time zones is enough to cause all new tokens to fail this validation even though the token is valid. Any help would be appreciated, thank you!

**Comment by nefilim** [comment]
Why is there a difference in timezones? Is this used in Android apps or something?

**Comment by ziek-za** [comment]
This is when testing locally, I am GMT+2.

**Comment by nefilim** [comment]
Are you using different libraries to issue and validate tokens? Can you give me an example of an issued token along with your current timestamp?

**Comment by sproctor** [comment]
I've opened #27 reporting the same issue. You can't use `LocalDateTime.now()` you need to specify the time zone as UTC. `LocalDateTime` is not a good data type for this application. `Instant` or `Long` would be more appropriate as they are time zone independent. Until this is changed get the current time with:

```kotlin
LocalDateTime.now(ZoneId.of("UTC"))
```

**Comment by nefilim** [comment]
@sproctor feel free to submit a PR - otherwise maybe I can get to this issue this weekend
